# NcatBot 基础配置文件
# 转发机器人 - Forward Bot

root: '123456'                    # ⚠️ 必须修改：Bot 管理员 QQ 号
bt_uin: '123456'                  # ⚠️ 必须修改：Bot QQ 号
enable_webui_interaction: false   # 启用 webui 交互
check_ncatbot_update: true        # 检查 NcatBot 更新
skip_ncatbot_install_check: false # 跳过 NcatBot 安装检查
debug: false                      # 调试模式

napcat:
  ws_uri: ws://localhost:3001     # NapCat WebSocket 地址
  webui_uri: http://localhost:6099 # NapCat WebUI 地址
  webui_token: napcat             # WebUI 认证令牌
  ws_token: '1234'                # WebSocket 认证令牌
  ws_listen_ip: localhost         # WebSocket 监听IP
  remote_mode: false              # 远程模式
  check_napcat_update: false      # 检查 NapCat 更新
  stop_napcat: false              # 停止 NapCat
  report_self_message: false      # 上报自身消息
  report_forward_message_detail: true # 上报解析合并转发消息

plugin:
  plugins_dir: plugins            # 插件目录
  skip_plugin_load: false         # 跳过插件加载