# 转发机器人专用配置文件
# Forward Bot Configuration

# 消息转发配置
forward:
  enabled: true                   # 是否启用转发功能
  send_interval: 500              # 转发间隔(毫秒)，防止频率过快
  
  # 转发规则列表
  rules:
    # 示例规则，实际使用时需要修改
    - name: "示例规则"            # 规则名称
      enabled: false              # 是否启用此规则
      type: "prefix"              # 过滤类型: "prefix"(前缀) 或 "keyword"(关键词)
      source_groups:              # 监听的源群号列表
        - 123456789
      target_groups:              # 转发到的目标群号列表  
        - 987654321
      keywords:                   # 前缀列表或关键词列表
        - "重要"
        - "紧急"
      forward_full_message: true  # 是否转发完整消息(包含图片等)
      preserve_format: true       # 是否保持原始格式
      forward_prefix: "[转发]"    # 转发前缀模板，支持变量 {source_group}

# 统计配置
statistics:
  enabled: true                   # 是否启用统计功能
  log_forward_events: true        # 记录转发事件到日志

# 管理员配置  
admin:
  # 有权使用管理命令的QQ号列表
  # 如果为空，则只有config.yaml中的root用户可以使用
  authorized_users: []
    # - 111111111
    # - 222222222

# 日志配置
logging:
  level: "INFO"                   # 日志级别: DEBUG, INFO, WARNING, ERROR
  log_file: "forward_bot.log"     # 日志文件名
  max_log_size: "10MB"           # 日志文件最大大小
  backup_count: 5                # 保留的日志文件数量